### ISSUE TITLE
关于ViewModel的一点困惑

### ISSUE THREAD

**Issue by xiaodongzai** [mmlpxjs/mmlpx#5]
Page interaction logic definition, live around the component lifecycle, ViewModel instance can not be stored in ioc container.

指的是依赖ViewModel的Compopent unmount后，ViewModel也会被销毁吗？但稍微看了源码（initializers目录下），还是没看明白，是怎么实现的, 它和Store的实现差异在哪里。希望得到大佬的解答。

**Comment by kuitos** [comment]
store是应用级单例的，通常放属于全局的业务状态，对应mvvm中的model。ViewModel是跟视图绑定，随视图创建销毁的，放局部的视图状态，对呀mvvm中的viewmodel

**Comment by xiaodongzai** [comment]
这个issues有讨论：https://github.com/mmlpxjs/mmlpx/issues/3
